######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 17 21:35:10 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tile.h
SOURCES += main.cpp tile.cpp
