######################################################################
# Automatically generated by qmake (3.0) Fri Feb 19 23:17:26 2016
######################################################################

TEMPLATE = app
TARGET = Eliminato
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += Board.h GameOverDialog.h MainWindow.h Tile.h
FORMS += gameoverdialog.ui mainwindow.ui
SOURCES += Board.cpp GameOverDialog.cpp main.cpp MainWindow.cpp Tile.cpp
